services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: llm_jupyter_lab
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONPATH=/usr/src/app
    command: ["jupyter", "lab", "--no-browser", "--allow-root", "--ip=0.0.0.0", "--NotebookApp.token=''", "--NotebookApp.password=''"]
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    volumes:
      - esdata:/usr/share/elasticsearch/data
    container_name: llm_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    mem_limit: 4g
  
volumes:
  esdata: